// Routes and API endpoints
export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  ASSESSMENT: '/assessment',
  JOBS: '/jobs',
  JOB_DETAIL: '/jobs/:id',
  ROADMAPS: '/roadmaps',
  ROADMAP_DETAIL: '/roadmaps/:id',
  INTERVIEWS: '/interviews',
  INTERVIEW_SESSION: '/interviews/:id',
  CONFIDENCE: '/confidence',
  SIMULATION: '/simulation',
  SETTINGS: '/settings',
  API: {
    AUTH: '/api/auth',
    USERS: '/api/users',
    ASSESSMENTS: '/api/assessments',
    JOBS: '/api/jobs',
    ROADMAPS: '/api/roadmaps',
    INTERVIEWS: '/api/interviews',
    AI: '/api/ai',
  },
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
  },
  USERS: {
    PROFILE: '/users/profile',
    ACCESSIBILITY: '/users/accessibility',
    PRIVACY: '/users/privacy',
    DELETE: '/users/account',
  },
  ASSESSMENTS: {
    LIST: '/assessments',
    CREATE: '/assessments',
    GET: '/assessments/:id',
    MESSAGE: '/assessments/:id/message',
    COMPLETE: '/assessments/:id/complete',
    HISTORY: '/assessments/history',
  },
  JOBS: {
    SEARCH: '/jobs',
    GET: '/jobs/:id',
    ANALYZE: '/jobs/:id/analyze',
    SAVED: '/jobs/saved',
    SAVE: '/jobs/:id/save',
    UNSAVE: '/jobs/:id/save',
  },
  ROADMAPS: {
    LIST: '/roadmaps',
    CREATE: '/roadmaps',
    GET: '/roadmaps/:id',
    UPDATE: '/roadmaps/:id',
    DELETE: '/roadmaps/:id',
    PROGRESS: '/roadmaps/:id/progress',
    COMPLETE_ITEM: '/roadmaps/:id/item/:itemId/complete',
  },
  INTERVIEWS: {
    LIST: '/interviews',
    CREATE: '/interviews',
    GET: '/interviews/:id',
    QUESTION: '/interviews/:id/question',
    RESPOND: '/interviews/:id/respond',
    PAUSE: '/interviews/:id/pause',
    RESUME: '/interviews/:id/resume',
    COMPLETE: '/interviews/:id/complete',
    FEEDBACK: '/interviews/:id/feedback',
  },
  AI: {
    CHAT: '/ai/chat',
    ANALYZE_JD: '/ai/analyze-jd',
    GENERATE_ROADMAP: '/ai/generate-roadmap',
    SUGGEST_CAREERS: '/ai/suggest-careers',
    GENERATE_QUESTIONS: '/ai/generate-questions',
    FEEDBACK: '/ai/feedback',
  },
} as const;

export const STORAGE_KEYS = {
  AUTH_TOKEN: 'ai4a_auth_token',
  REFRESH_TOKEN: 'ai4a_refresh_token',
  USER_PROFILE: 'ai4a_user_profile',
  ACCESSIBILITY_SETTINGS: 'ai4a_accessibility',
  LANGUAGE: 'ai4a_language',
  THEME: 'ai4a_theme',
} as const;

export const DEFAULT_ACCESSIBILITY_SETTINGS = {
  fontSize: 100,
  highContrast: false,
  reducedMotion: false,
  voiceNavigation: false,
  keyboardOnly: false,
  screenReaderOptimized: false,
  extraTime: false,
  preferredInput: 'text' as const,
};
